// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for suggesting initial inquiries to a seller.
 *
 * It includes:
 * - `suggestInitialInquiry`: An async function that takes product details and returns a suggested inquiry.
 * - `SuggestInitialInquiryInput`: The input type for `suggestInitialInquiry`, including product name and description.
 * - `SuggestInitialInquiryOutput`: The output type for `suggestInitialInquiry`, a string representing the suggested inquiry.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestInitialInquiryInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productDescription: z.string().describe('A detailed description of the product.'),
});
export type SuggestInitialInquiryInput = z.infer<
  typeof SuggestInitialInquiryInputSchema
>;

const SuggestInitialInquiryOutputSchema = z.object({
  suggestedInquiry: z
    .string()
    .describe('A suggested initial inquiry to send to the seller.'),
});
export type SuggestInitialInquiryOutput = z.infer<
  typeof SuggestInitialInquiryOutputSchema
>;

export async function suggestInitialInquiry(
  input: SuggestInitialInquiryInput
): Promise<SuggestInitialInquiryOutput> {
  return suggestInitialInquiryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestInitialInquiryPrompt',
  input: {schema: SuggestInitialInquiryInputSchema},
  output: {schema: SuggestInitialInquiryOutputSchema},
  prompt: `You are an AI assistant helping buyers connect with sellers on a B2B marketplace.
  Your task is to suggest an initial inquiry message that a buyer can send to a seller regarding a specific product.
  The inquiry should be professional, concise, and aimed at gathering essential information.

  Product Name: {{{productName}}}
  Product Description: {{{productDescription}}}

  Suggested Inquiry:`, //Crucially, the prompt object wraps a string prompt (keyed by `prompt`)
});

const suggestInitialInquiryFlow = ai.defineFlow(
  {
    name: 'suggestInitialInquiryFlow',
    inputSchema: SuggestInitialInquiryInputSchema,
    outputSchema: SuggestInitialInquiryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
